2420 Assignment1, Part2 final submission scripts and zip

diff --git a/2420/project_scripts/notes-cli-rs b/2420/project_scripts/notes-cli-rs
--- a/2420/project_scripts/notes-cli-rs
+++ b/2420/project_scripts/notes-cli-rs
@@ -8,6 +8,26 @@
 #:               -m for searching with titles
 #:               -d for searching with dates
 
+#######################################
+# log error messages
+# Arguments:
+#   message to log
+# Outputs:
+#   log message passed as argument
+#######################################
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+}
+
+#######################################
+# Find the notes matching the search
+# and print them out. 
+# Arguments:
+#   None
+# Outputs:
+#   The files containing the search
+#   term. 
+#######################################
 find() {
   NOTE=$(grep -rl $1 ~/notes/* | awk '{ print $5 }' FS=/)
   echo "The following files match the search term: "
@@ -16,6 +36,13 @@ find() {
   done
 }
 
+#######################################
+# Print a Usage message.
+# Arguments:
+#   None
+# Outputs:
+#   Write a help message
+#######################################
 usage() {
   echo -e "Usage: notes-cli-rs [-t|-m|-d] \e[4mNOTE_NAME\e[0m"
   echo 'Description: Read and search for notes.'
@@ -26,7 +53,7 @@ usage() {
 }
 
 
-# OPTIONS
+# OPTIONS HANDLING
 while getopts "t:m:d:" opt; do
   case ${opt} in
     t) #find with tags
@@ -57,6 +84,6 @@ if [[ -f $HOME/notes/$1 ]]; then
   echo -e "\e[4mContents of $1:\e[0m"
   cat $HOME/notes/$1
 else
-  echo "Error: $1 doesn't exist."
+  err "Error: $1 doesn't exist."
   exit 1
 fi
diff --git a/2420/project_scripts/notes-cli-write b/2420/project_scripts/notes-cli-write
--- a/2420/project_scripts/notes-cli-write
+++ b/2420/project_scripts/notes-cli-write
@@ -8,19 +8,20 @@
 
 #######################################
 # log additional messages
-# locals:
-#   MESSAGE
 # Arguments:
 #   message to log
 # Outputs:
 #   log message passed as argument
 #######################################
-log() {
-  local MESSAGE="${@}"
-  # if [[ "${VERBOSE}" = 'true' ]]; then
-  echo "${MESSAGE}"
-  # fi
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
 }
+
+# if a user passes a positional arugment, err
+if [[ $# -gt 0 ]]; then
+  err "This script doesn't take any arguments!"
+  exit 1
+fi
 
 # Make the notes directory if it doesn't exit
 if [[ ! -d "$HOME/notes" ]]; then
@@ -28,18 +29,19 @@ if [[ ! -d "$HOME/notes" ]]; then
   mkdir $HOME/notes
 fi
 
-# Read the user input for title and tags
+# Read the user input for title
 read -p $'Please Enter a \e[4mTitle:\e[0m ' TITLE
 
-# Create the filename with the date and time appended at the end
-if [[ -f $TITLE ]]; then
-  log "Error: A note with the same title already exists in the notes folder."
-  log "Exiting. Please try again!"
-  exit 1
+# Create the filename with the given title, asking again if it already exists.
+if [[ -f $HOME/notes/$TITLE ]]; then
+  err "Error: A note with the same title already exists in the notes folder."
+  read -p $'Please Enter a \e[4mTitle:\e[0m ' TITLE
 fi
 
 touch "$HOME/notes/$TITLE"
 
+
+# Read the tags. 
 echo "Enter tags separated by spaces: "
 echo "Press CTRL+D on new line to finish."
 echo -en "\e[4mTags:\e[0m "
@@ -57,6 +59,8 @@ for tag in ${TAGS[@]}; do
 done
 echo "" >> "${HOME}/notes/${TITLE}"
 echo -e "\e[4mDate\e[0m: $(date "+%F %H:%M:%S")" >> "${HOME}/notes/${TITLE}"
+
+# Read the not from stdin until CTRL+D is hit. 
 echo "Please enter the note, presss CTRL+D on new line to finish."
 NOTE=$(</dev/stdin)
 echo "$NOTE" >> "${HOME}/notes/${TITLE}" 
diff --git a/2420/project_scripts/sys-info b/2420/project_scripts/sys-info
--- a/2420/project_scripts/sys-info
+++ b/2420/project_scripts/sys-info
@@ -20,6 +20,17 @@ usage() {
   exit 1
 }
 
+#######################################
+# log additional messages
+# Arguments:
+#   message to log
+# Outputs:
+#   log message passed as argument
+#######################################
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+}
+
 # Variables to use in printing system info
 HOSTNAME=$(hostname | awk '{ print $1 }' FS=.)
 USER=$(whoami)
@@ -89,7 +100,7 @@ while getopts "t" opt; do
       PRINT_VER="print_tux"
       ;;
     \?)
-      echo "Error: Invalid Option"
+      err "Error: Invalid Option"
       usage
       exit 1
       ;;
